#ifndef VERIFICATION_CONFIG_H
#define VERIFICATION_CONFIG_H

#define VERIFICATION_ENABLE_TIMING
#define VERIFICATION_ENABLE_TRACING
#define VERIFICATION_ENABLE_CHECKING

#endif // VERIFICATION_CONFIG_H
